AT 03.07.01 | Multi-configuration Project > Delete Multi-configuration Project
RedRoverSchool/JenkinsQA_05 pull request #1018
Opened 2022-12-11 07:09 UTC by zkonovalova78

2022-12-11 15:01 UTC, kirin608 approved these changes

2022-12-11 16:41 UTC, olpolezhaeva commented on src/test/java/MulticonfigurationProjectTest.java
> +        getDriver().findElement(By.xpath("//tr[@id = 'job_"+PROJECT_NAME+"']/descendant::td//button")).click();
Через String.format лучше:
getDriver().findElement(By.xpath(String.format("//tr[@id = 'job_%s']/descendant::td//button", PROJECT_NAME))).click();

2022-12-12 06:07 UTC, zkonovalova78 commented on src/test/java/MulticonfigurationProjectTest.java
> +        getDriver().findElement(By.xpath("//tr[@id = 'job_"+PROJECT_NAME+"']/descendant::td//button")).click();
Спасибо!

2022-12-19 01:54 UTC, cyferkiBY approved these changes

2022-12-19 01:55 UTC, cyferkiBY commented
Перед мержем проверьте, возможно ваш тест уже отрефакторили под POM. Если это так, то пожалуйста, закройте PR.

2022-12-19 02:03 UTC, cyferkiBY reviewed
CI падает, поэтому вынуждена отозвать свой аппрув.

2022-12-19 02:04 UTC, cyferkiBY requested changes
Перед мержем проверьте, возможно ваш тест уже отрефакторили под POM. Если это так, то пожалуйста, закройте PR. Кроме того CI падает.

2022-12-30 19:09 UTC, closed without merging