creating abstract classes for POM
RedRoverSchool/JenkinsQA_05 pull request #1074
Opened 2022-12-13 09:29 UTC by SergeDot

making changes in some tests to match the abstract classes changing unreliable button clicks to button submits

2022-12-13 14:04 UTC, gdikhsanov commented on src/test/java/model/ViewPage.java
> +//    }
Уберите, пож. закомментированный код

2022-12-13 15:57 UTC, SergeDot commented on src/test/java/model/ViewPage.java
> +//    }
> Уберите, пож. закомментированный код

Готово

2022-12-13 20:01 UTC, SergeiDemyanenko requested changes

2022-12-13 20:01 UTC, SergeiDemyanenko commented on src/test/java/model/base/SideMenuFrame.java
> +public abstract class SideMenuFrame extends MainPage {
Почему у тебя часть страницы наследуется от страницы?

2022-12-13 20:01 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseModel.java
> +    public Actions getAction() {
Зачем это изменение?

2022-12-13 20:22 UTC, SergeDot commented on src/test/java/runner/BaseModel.java
> +    public Actions getAction() {
> Зачем это изменение?

Моя ошибка, в какой-то момент неужно было, забыл обратно поменять, исправил

2022-12-13 20:26 UTC, SergeDot commented on src/test/java/model/base/SideMenuFrame.java
> +public abstract class SideMenuFrame extends MainPage {
> Почему у тебя часть страницы наследуется от страницы?
Чтобы в страницах наследующихся от SideMenuFrame был доступ к общим элементам и к пунктам меню. Это правильный способ?

2022-12-14 00:43 UTC, SergeiDemyanenko commented on src/test/java/model/base/SideMenuFrame.java
> +public abstract class SideMenuFrame extends MainPage {
Страницы не могут наслодоваться от Frame т.к. Frame это не страница или у тебя это страница?

2022-12-14 00:47 UTC, SergeDot commented on src/test/java/model/base/SideMenuFrame.java
> +public abstract class SideMenuFrame extends MainPage {
> Страницы не могут наслодоваться от Frame т.к. Frame это не страница или у тебя это страница?

По факту не страница. Так как мне в таком случае нужно будет делать наследование от 2-х классов, лучше будет переписать с помощью такой конструкции? public abstract class BaseBuildPage<Self extends BaseBuildPage<?, ?>, SideMenu> extends BaseSideMenuPage<Self, SideMenu>

2022-12-14 18:23 UTC, closed without merging