Ya 00.01.001
RedRoverSchool/JenkinsQA_05 pull request #1128
Opened 2022-12-16 10:49 UTC by Alex-apple1

Hi anyone! Please check my code so I can merge it to the main line.

2022-12-16 21:22 UTC, UmidaKaharova commented on src/test/java/NewFolderTest.java
> +//        Assert.assertEquals(actualFolderName, folder2Name);
Почему закомментили ассерт?

2022-12-16 21:24 UTC, UmidaKaharova commented on src/test/java/NewFolderTest.java
> +        String welcomeNote = "Добро пожаловать в Jenkins!";
Так как у большинства дженкинс на англ, этот тест может упасть

2022-12-16 21:25 UTC, UmidaKaharova commented on src/test/java/NewFreeStyleProjectALEXTest.java
> +                .clickGithubCheckbox()
Тут специально 2 раза вызываете 1 метод?

2022-12-16 21:27 UTC, UmidaKaharova commented on src/test/java/NewFreeStyleProjectALEXTest.java
> +//        String actualText = new HomePage(getDriver()).getHomePageWelcomeText();
Без комментов пожалуйста

2022-12-16 21:29 UTC, UmidaKaharova commented on src/test/java/model/FreeStyleProjectMenuPage.java
> +    private WebElement topMenuRoot;
Оставьте пустые линии через каждый @FindBy

2022-12-16 21:30 UTC, UmidaKaharova commented on src/test/java/model/HomePage.java
> +
Без комментов пожалуйста

2022-12-16 21:31 UTC, UmidaKaharova commented on src/test/java/model/NewItemPage.java
> +//    private WebElement okButton;
Без комментов пожалуйста

2022-12-16 21:33 UTC, UmidaKaharova requested changes
Поменяйте название PR на более правильный и добавьте карточку трелло

2022-12-17 02:41 UTC, cyferkiBY commented on src/test/java/old/NoGroupTest.java
> +package old;
Зачем вы создаете пакет old и добавляете туда заигноренный класс NoGroupTest ?

2022-12-17 10:38 UTC, Alex-apple1 commented on src/test/java/NewFolderTest.java
> +//        Assert.assertEquals(actualFolderName, folder2Name);
Прошу прощения - я и сам тест забросил)) Прошулся - все поправил. Сейчас апдейтну - может пройдет воркфлоу

2022-12-17 10:39 UTC, Alex-apple1 commented on src/test/java/NewFolderTest.java
> +        String welcomeNote = "Добро пожаловать в Jenkins!";
Согласен. Переделал на то, что будет работать точно! И у меня и у всех.

2022-12-17 10:39 UTC, Alex-apple1 commented on src/test/java/NewFreeStyleProjectALEXTest.java
> +                .clickGithubCheckbox()
Да. Просто щелкнул. Потом отщелкнул. Такое можно делать?))

2022-12-17 10:40 UTC, Alex-apple1 commented on src/test/java/NewFreeStyleProjectALEXTest.java
> +//        String actualText = new HomePage(getDriver()).getHomePageWelcomeText();
Сорри - забыл подчистить...

2022-12-17 10:42 UTC, Alex-apple1 commented on src/test/java/model/FreeStyleProjectMenuPage.java
> +    private WebElement topMenuRoot;
Ок. Сделаю. Просто когда появились серые usage плюс пустая строка так код вообще растянулся и расстояния между методами или полями увеличилось. Зрительно выглядит как просто огромные пустые пространства и долистать до конца или нужной строки становится сложнее и дольше... Но сделаю как надо.

2022-12-17 10:43 UTC, Alex-apple1 commented on src/test/java/model/HomePage.java
> +
Сорри... мусорю...Надо клинкод.

2022-12-17 10:43 UTC, Alex-apple1 commented on src/test/java/model/NewItemPage.java
> +//    private WebElement okButton;
да блин...

2022-12-17 10:44 UTC, Alex-apple1 commented on src/test/java/old/NoGroupTest.java
> +package old;
Спецом не создавал. Может он у меня из моей ветки вывалился - я давно не пушился. Сейчас уберу...

2022-12-30 19:09 UTC, closed without merging