RF | FreestyleConfigSideMenuPage> Refactor
RedRoverSchool/JenkinsQA_05 pull request #1238
Opened 2023-01-04 07:31 UTC by janarkqa

https://trello.com/c/eUCZm9xW/1142-rf-freestyleconfigsidemenupage-refactor

- Создан BaseConfigSideMenuFrame, от которого наследуются FreestyleProjectConfigSideMenuFrame(для FreestyleProjectConfigPage) и MainConfigSideMenuFrame(для остальных конфигурационных страниц).
По мере необходимости будем создавать другие боковые меню (например, FolderConfigSideMenuFrame, PipelineConfigSideMenuFrame и т.п.), наследовать их от BaseConfigSideMenuFrame и имплементировать абстрактные методы и возможно в конце удалим MainConfigSideMenuFrame.
- В BaseConfigPage создан метод перехода в боковое меню getSideMenu(), который собственно переходит с конфигурационной страницы в панель меню.
- Для возврата конфигурационной страницы в методах бокового меню используем переменную configPage, которая находится в BaseConfigSideMenuFrame и является protected.

2023-01-07 18:49 UTC, kartavenkopavel approved these changes

2023-01-08 00:49 UTC, InnaRomankova approved these changes

2023-01-08 01:19 UTC, SergeiDemyanenko requested changes
Reviewing...

2023-01-08 02:00 UTC, SergeiDemyanenko approved these changes
Я заапрувил PR, но посмотри омментарии, если понятно и можешь переделать, то сделай, а если что-то не понятно, что можно слить и так и потом исправить.

2023-01-08 02:00 UTC, SergeiDemyanenko commented on src/test/java/model/base/BaseConfigSideMenuFrame.java
> +public abstract class BaseConfigSideMenuFrame<ConfigPage extends BaseConfigPage<?, ?, ?>> extends BaseModel {
Класс выглядит так, как будто это Базовое меню вообще, а не только для Config. Может стоит сделать BaseSideMenuFrame и уже от него наследовать BlankConfigSideMenuFrame или PlaneConfigSideMenuFrame? Это не деректива, просто спрашиваю :)

2023-01-08 02:00 UTC, SergeiDemyanenko commented on src/test/java/model/MainConfigSideMenuFrame.java
> +public class MainConfigSideMenuFrame<ConfigPage extends BaseConfigPage<?, ?, ?>> extends BaseConfigSideMenuFrame<ConfigPage> {
Может назвать BlankConfigSideMenuFrame или PlaneConfigSideMenuFrame? Я знаю, что я сам предложил Main, но что-то как-то мне не очень, но решать тебе.

2023-01-08 02:00 UTC, SergeiDemyanenko commented on src/test/java/model/base/BaseConfigPage.java
> +    protected abstract ConfigSideMenuFrame createConfigSideMenuFrame();
Мы уже и так в елассе конфигурации, может назвать просто: createSideMenuFrame?

2023-01-08 02:00 UTC, SergeiDemyanenko commented on src/test/java/model/folder/FolderConfigPage.java
> +    protected MainConfigSideMenuFrame<FolderConfigPage> createConfigSideMenuFrame() {
Этот метод будет повторяться в большенстве наследников, было бы логично сделать промежуточный класс BlankConfigPage или PlaneConfigPage с уже предуствновленным меню и перелпределенноым методом.

2023-01-08 02:19 UTC, janarkqa commented on src/test/java/model/base/BaseConfigSideMenuFrame.java
> +public abstract class BaseConfigSideMenuFrame<ConfigPage extends BaseConfigPage<?, ?, ?>> extends BaseModel {
У нас будет еще side menu для status page-в, там видно будет. Этот создавался именно для Config.

2023-01-08 03:56 UTC, merged