AT_01.06.03.1_Freestyle Project Rename Freestyle Project to incorrect
RedRoverSchool/JenkinsQA_05 pull request #1334
Opened 2023-01-27 03:02 UTC by ViktoriyaED

testRenameFreestyleProjectToIncorrect added

[TC] https://trello.com/c/cPxW8GvX/488-tc-010603-freestyle-project-rename-freestyle-project-to-incorrect
[AT] https://trello.com/c/bic5dwk6/1254-at-0106031-freestyle-project-rename-freestyle-project-to-incorrect

2023-01-27 03:07 UTC, TinaQA approved these changes

2023-01-27 09:06 UTC, kartavenkopavel commented on src/test/java/tests/FreestyleProjectTest.java
> +        CreateItemErrorPage createItemErrorPage = new CreateItemErrorPage(getDriver());
Если rename приводит к ошибки, создана  RenameItemErrorPage. CreateItemErrorPage для других случаев. И цепочку нужно начинать с того к чему она должна прийти, чтобы несколько раз не вызывать драйвер.

2023-01-27 09:07 UTC, kartavenkopavel commented on src/test/java/tests/FreestyleProjectTest.java
> +    public void testRenameFreestyleProjectToIncorrect() {
Чтобы не плодить однотипные тесты можно сделать дата провайдер и проверить поле на все некорректные символы. Соответственно нужно переименовать тест.

2023-01-27 09:12 UTC, kartavenkopavel requested changes
PR получил approve от человека, который не участвует в проекте. В следующий раз за такое будет удаление из репозитория. Название ветки не соответсвует правилам проекта.

2023-01-28 08:14 UTC, kartavenkopavel approved these changes

2023-01-28 14:20 UTC, merged