https://trello.com/c/R9VZvke0/1247-at-030608-multiconfiguration-proje…
RedRoverSchool/JenkinsQA_05 pull request #1344
Opened 2023-01-29 15:51 UTC by ArailymAsar

…ct-configure-set-configuration-matrix-build-stages

2023-02-01 14:30 UTC, DenSebrovsky commented on src/test/java/model/config_pages/MultiConfigurationProjectConfigPage.java
> +    @FindBy(xpath = "//*[@id=\"main-panel\"]/form/div[1]/div[10]/div[2]/div/div/div[1]/div/div[5]/div/span[contains(@class, 'advancedButton')]")
Привет! Попробуй поменять кавычки внутри xpath: вместо \" поставь '

2023-02-01 16:34 UTC, cyferkiBY commented on src/test/java/model/config_pages/MultiConfigurationProjectConfigPage.java
> +    private WebElement AdvancedBuildStepsButton;
Имя переменной не может быть с большой буквы

2023-02-01 16:34 UTC, cyferkiBY commented on src/test/java/model/config_pages/MultiConfigurationProjectConfigPage.java
> +    private WebElement AdvancedBuildStepsButton;
и такой локатор уже есть.

2023-02-01 16:34 UTC, cyferkiBY commented on src/test/java/model/config_pages/MultiConfigurationProjectConfigPage.java
> +        AdvancedBuildStepsButton.click();
Отрефакторили работу с кнопкой Advanced. Используй, пожалуйста, здесь метод clickLastAdvancedButtonInBuildStepsSection().

2023-02-02 09:03 UTC, kartavenkopavel requested changes
PR висит уже 3 дня, @ArailymAsar ведется работа над исправлением? И в тестах опять зависимости, от которых мы столько времени избавлялись.

2023-02-15 06:16 UTC, closed without merging