Mj/new test
RedRoverSchool/JenkinsQA_05 pull request #42
Opened 2022-11-02 18:25 UTC by MariJern

Added new test "MariJernTest".

2022-11-02 19:06 UTC, iKrlkv requested changes
It's better not to put Thread.Sleep in your PR to avoid redundant waiting of CI test runs.

2022-11-02 19:49 UTC, codeRedMichael approved these changes

2022-11-02 21:27 UTC, MariJern commented
Reopening closed PR #42

2022-11-03 02:55 UTC, SergeiDemyanenko approved these changes

2022-11-03 03:50 UTC, merged