AT 04.03 | Folder > Add folder description
RedRoverSchool/JenkinsQA_05 pull request #530
Opened 2022-11-16 16:48 UTC by EvgeniyaPiskunova

https://trello.com/c/Nh5XrBBW/90-at-0403-folder-add-folder-description

2022-11-16 20:00 UTC, SergeiDemyanenko approved these changes

2022-11-16 20:02 UTC, SergeiDemyanenko requested changes

2022-11-16 20:02 UTC, SergeiDemyanenko commented on src/test/java/FolderTest.java
> +    public void configureFolderAddDescription() {
Название не отражает содержимое.

2022-11-16 21:34 UTC, julykan approved these changes

2022-11-16 21:35 UTC, julykan approved these changes

2022-11-16 21:35 UTC, EvgeniyaPiskunova commented on src/test/java/FolderTest.java
> +    public void configureFolderAddDescription() {
исправила

2022-11-17 05:16 UTC, ke-de-ve approved these changes

2022-11-17 05:53 UTC, InnaRomankova approved these changes

2022-11-17 07:23 UTC, MykhailoMo reviewed
@EvgeniyaPiskunova а почему на доске Трело ТС и АТ карточки в столбце ToDo висят? Как я понял, ТС должна в Done а АТ в InReview.

2022-11-17 07:26 UTC, EfanovaVikky approved these changes

2022-11-17 14:18 UTC, EvgeniyaPiskunova commented
> @EvgeniyaPiskunova а почему на доске Трело ТС и АТ карточки в столбце ToDo висят? Как я понял, ТС должна в Done а АТ в InReview.

все поставила в нужные столбики

2022-11-17 14:25 UTC, MykhailoMo approved these changes

2022-11-17 15:49 UTC, SergeiDemyanenko approved these changes

2022-11-17 15:58 UTC, merged