AT 00.05.02 Create new mb pipeline with empty name test
RedRoverSchool/JenkinsQA_05 pull request #534
Opened 2022-11-16 20:45 UTC by judmi

2022-11-16 20:50 UTC, judmi commented
![](https://github.trello.services/images/mini-trello-icon.png) [AT 00.05.02 | New Item > Multibranch Pipeline | Create new mb pipeline with empty name](https://trello.com/c/5sIG2uvQ/109-at-000502-new-item-multibranch-pipeline-create-new-mb-pipeline-with-empty-name)

2022-11-17 09:13 UTC, Folevald requested changes
TC changing is required

2022-11-17 10:09 UTC, Folevald approved these changes

2022-11-17 10:23 UTC, Reinar47 approved these changes

2022-11-17 10:25 UTC, merged