TC 04.01.02 | Folder > Create folder in folder
RedRoverSchool/JenkinsQA_05 pull request #605
Opened 2022-11-19 19:00 UTC by iKrlkv

<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;wF2vFO0i&#x2F;304-at-040102-folder-create-folder-in-folder">AT 04.01.02 | Folder &gt; Create folder in folder</a></blockquote>

2022-11-19 19:17 UTC, iKrlkv commented
![](https://github.trello.services/images/mini-trello-icon.png) [AT 04.01.02 | Folder > Create folder in folder](https://trello.com/c/wF2vFO0i/304-at-040102-folder-create-folder-in-folder)

2022-11-19 21:05 UTC, darinamas requested changes

2022-11-19 21:05 UTC, darinamas commented on src/test/java/CreateFolderWithDescriptionTest.java
>          getDriver().findElement(By.xpath(String.format("//span[text()='%s']", FOLDERNAME))).click();
Please don't create extra classes. Please move testCreateFolderWithDescription() test to FolderTest class and delete CreateFolderWithDescriptionTest.

2022-11-20 07:53 UTC, Tchernomor approved these changes

2022-11-20 08:00 UTC, Snegafal approved these changes

2022-11-20 11:26 UTC, darinamas approved these changes

2022-11-20 12:12 UTC, merged