ERR | MultibranchPipelineTest > Rename_Multibranch_Pipeline_Test
RedRoverSchool/JenkinsQA_05 pull request #711
Opened 2022-11-23 15:49 UTC by Reinar47

https://trello.com/c/mg0uVxu7/476-err-multibranchpipelinetest-renamemultibranchpipelinetest

2022-11-23 16:31 UTC, dmcalifornia approved these changes

2022-11-24 23:14 UTC, cyferkiBY requested changes
Ошибка не исправлена. Прочитайте комментарий. Кстати, при поиске элемента на дашборде учтите, что он может оказаться внизу списка (вне области отображения), и прежде чем по нему кликнуть необходимо проскролить страницу. Из-за того что многие это не учитывают, тесты получаются нестабильные и постоянно падают (если сгенерированное имя элемента оказывается внизу дашброда).

2022-11-24 23:14 UTC, cyferkiBY commented on src/test/java/MultibranchPipelineTest.java
>                  (By.xpath("//a [@class='jenkins-table__link model-link inside']")).click();
Вы не верно локализовали ошибку. Ваша ошибка еще в этой строке. Некорректный xpath.  Вы фактически кликаете по первому элементу на дашборде (какой бы он не был), а должны искать на дашборде именно ваш созданный элемент MultibranchPipeline и кликать по нему. Сейчас если на дашборде будет хоть один ранее созданный элеменет (например только в этом классе их создается много), то вы кликаете по первому из них, а он оказывается не типа пайплайн, поэтому тест падает - там другие локаторы и другой путь для переименования.

2022-11-24 23:14 UTC, cyferkiBY commented on src/test/java/MultibranchPipelineTest.java
> +        getDriver().findElement(By.xpath("//div [@class='task '][8]")).click();
Плохой xpath, старайтесь если возможно не привязываться к порядку, если изменится порядок вы даже не поймете что кликнули не туда и тест поломается. В идеале гляда на xpath должно быть понятно что за он. Я бы здесь использовала что-то типа` //div[@class='task ']//a[contains(@href, "move")]`.

2022-11-25 20:39 UTC, cyferkiBY commented on src/test/java/MultibranchPipelineTest.java
>                  (By.xpath("//a [@class='jenkins-table__link model-link inside']")).click();
В принципе, сейчас, после вчерашних изменений Сергея, когда все Jobs удаляются перед запуском теста внесение этих изменений не критично. В рамках вашего теста у вас всегда будет первым и единственным элементом на дашборде ваш. Однако рекомендую все же написать корректный локатор для поиска именно вашего созданного item, т.к. ваш тест могут использовать как dependence. Поэтому раз вы все таки решаете своим PR ошибку попробуйте решить её до конца.

2022-11-26 17:58 UTC, closed without merging