TC 03.06.09 | Multiconfiguration Project > Configure
RedRoverSchool/JenkinsQA_05 pull request #758
Opened 2022-11-26 17:48 UTC by bahasadyr

https://trello.com/c/3FY8lhJC/569-tc-030609-multiconfiguration-project-configure

2022-11-26 17:54 UTC, bahasadyr commented
AT 03.06.09 | Multiconfiguration Project > Configure

2022-11-26 18:07 UTC, olpolezhaeva commented
В заголовке нужно изменить на AT 03.06.09
После Configure у вас нет сути, что тест делает. В Тест-кейсе и в карточке AT вам это нужно дописать в заголовке.

2022-11-26 22:46 UTC, bahasadyr commented
> 

Added AT to the headers. Refactored TC according reviewer's comments. Closed PR which was opened a week ago

2022-11-27 10:28 UTC, olpolezhaeva commented
@bahasadyr Ок! А теперь почему карточка AT 03.06.09 | Multiconfiguration Project > Configure не содержит add description?
И почему она находится в колонке backlog?

2022-11-27 13:14 UTC, olpolezhaeva requested changes
Приведите, пожалуйста, карточки в Trello в порядок и дождитесь review на TC

2022-11-27 17:25 UTC, bahasadyr commented
> @bahasadyr Ок! А теперь почему карточка AT 03.06.09 | Multiconfiguration Project > Configure не содержит add description? И почему она находится в колонке backlog, не имеет вложений TC и US и вы к ней не присоединились? Получено ли review на TC?

I Added description to AT and TC 03.01.09. Added PR link to AT card. Added TC and US connection to AT. Sorry, I dont have russian keyboard here, only on the phone (

2022-11-27 23:49 UTC, bahasadyr commented
> Приведите, пожалуйста, карточки в Trello в порядок и дождитесь review на TC

refactored cards in Trello , got approval for this TC : 
https://trello.com/c/3FY8lhJC/569-tc-030109-multi-configuration-project-configure-add-description

2022-11-30 09:45 UTC, olpolezhaeva commented
Заголовок этого пулл реквеста все еще отличается т карточки.AT 03.01.09 или AT 03.06.09?

2022-11-30 09:45 UTC, olpolezhaeva approved these changes

2022-11-30 17:06 UTC, bahasadyr commented
> Заголовок этого пулл реквеста все еще отличается т карточки.AT 03.01.09 или AT 03.06.09?

@olpolezhaeva sorry for the confusion, but AT 03.06.09 is for different TC (https://trello.com/c/JHkh7LJZ/208-tc-030602-multiconfiguration-project-configure) which I havent started to work on it  yet

2022-11-30 18:06 UTC, veronmolosh approved these changes
Looks good!
Maybe I little changed this 
getDriver().findElement(By.xpath("**//textarea[@name='description']"**)).sendKeys(multiConfProjectDescriptionText);
on 
getDriver().findElement(By.name("description")).sendKeys(multiConfProjectDescriptionText);
If it does not interfere with the locator, but this is a matter of taste : )

2022-11-30 18:10 UTC, bahasadyr commented
> Looks good! Maybe I little changed this getDriver().findElement(By.xpath("**//textarea[@name='description']"**)).sendKeys(multiConfProjectDescriptionText); on getDriver().findElement(By.name("description")).sendKeys(multiConfProjectDescriptionText); If it does not interfere with the locator, but this is a matter of taste : )

@veronmolosh there was another  locator with description on this page ,as I remember

2022-11-30 18:10 UTC, merged