AT 01.03.01 Freestyle Project > Build Freestyle in Folder
RedRoverSchool/JenkinsQA_05 pull request #788
Opened 2022-11-28 18:19 UTC by ar1a00

Freestyle Project Build in Folder. Dependent Tests. First Edition

2022-11-28 18:19 UTC, ar1a00 commented
![](https://github.trello.services/images/mini-trello-icon.png) [AT 01.03.01 Freestyle Project> Build Freestyle in Folder](https://trello.com/c/ClClb0w9/634-at-010301-freestyle-project-build-freestyle-in-folder)

2022-12-02 01:16 UTC, UmidaKaharova commented
Пожалуйста, используйте wait вместо sleep. 
Почему вы вывели в константу элементы, которые вы используете не больше 1ого раза?

2022-12-02 02:01 UTC, UmidaKaharova requested changes
1. Пожалуйста, используйте wait вместо sleep.
2. Почему вы вывели в константу элементы, которые вы используете не больше 1ого раза?
3. "//*[contains(@id, 'yui-gen') and contains(@type,'submit')]"
Этот xpath можно заменить на By.id("yui-gen"). Cтарайтесь избегать * в xpath

2022-12-05 19:44 UTC, UmidaKaharova approved these changes

2022-12-05 21:13 UTC, snysmymric commented
Если , просим approve то карточка AT должна быть в колонке InReview. Я переместила, замечание на будущее.

2022-12-05 21:16 UTC, snysmymric commented
класс folderWithDescription.java был удален осознанно, верно?

2022-12-05 21:29 UTC, kirin608 reviewed
нужны отступы (пустые строчки) перед @TEST
1
  private static String name = "project-" + x;
    @Test
    public void createFolderTest() {


2    
                    By.cssSelector("#view-message")).getText().contains(DESCRIPTION));
    }
    @Test(dependsOnMethods = {"createFolderTest"})
    public void testCreateFreestyleProject() {
    
    Назване класса должно заканчиватся на "Test"

2022-12-05 22:17 UTC, snysmymric requested changes
поправь пож все замечания особенно LockSupport.parkNanos(TimeUnit.MILLISECONDS.toNanos(3000)); все остальные больше косметика

2022-12-05 22:17 UTC, snysmymric commented on src/test/java/FreestyleBuildInFolder.java
> +        LockSupport.parkNanos(TimeUnit.MILLISECONDS.toNanos(3000));
Сергей сказал так делать не надо , воспользуйся пожалуйста методом getWait(int seconds) из BaseTest

2022-12-06 00:32 UTC, ar1a00 commented on src/test/java/FreestyleBuildInFolder.java
> +    @Test(dependsOnMethods = {"createFolderTest"})
Почему? Отлично работает с фигурными скобками. Я googled больше с {}, чем без в синтаксисе

2022-12-23 11:47 UTC, closed without merging