TC 01.04.11 | Freestyle project > Configure > Validate that selected "Build periodically" checkbox is selected
RedRoverSchool/JenkinsQA_05 pull request #867
Opened 2022-12-01 17:19 UTC by InnaRomankova

[TC] - https://trello.com/c/ycsejQJr

2022-12-01 20:58 UTC, Stanislaw1349 approved these changes
LGTM

2022-12-01 20:59 UTC, Stanislaw1349 requested changes
не нужно использовать Sleep
пожалуйста, воспользуйтесь  Wait

2022-12-02 01:38 UTC, kirin608 commented
уберите Thread Sleep.
Change required

2022-12-02 01:39 UTC, kirin608 requested changes
уберите Thread Sleep.
Change required

2022-12-02 07:43 UTC, InnaRomankova commented
> не нужно использовать Sleep пожалуйста, воспользуйтесь Wait



> не нужно использовать Sleep пожалуйста, воспользуйтесь Wait

Я пробовала 2 варианта Wait, наиболее подходящие по смыслу, они не срабатывают:
getWait(10).until(ExpectedConditions
                .elementToBeClickable(By.xpath("//label[text()='Build periodically']")));
getWait(10).until(ExpectedConditions
                .presenceOfElementLocated(By.xpath("//label[text()='Build periodically']")));
...

Implicit Wait тоже не срабатывает в этом случае в CI. Локально у меня все проходит без Waits.
Может вы подскажете, что можно еще попробовать в данном случае?

2022-12-02 07:44 UTC, InnaRomankova commented
> не нужно использовать Sleep пожалуйста, воспользуйтесь Wait


Я пробовала 2 варианта Wait, наиболее подходящие по смыслу, они не срабатывают:
getWait(10).until(ExpectedConditions
                .elementToBeClickable(By.xpath("//label[text()='Build periodically']")));
getWait(10).until(ExpectedConditions
                .presenceOfElementLocated(By.xpath("//label[text()='Build periodically']")));
...

Implicit Wait тоже не срабатывает в этом случае в CI. Локально у меня все проходит без Waits.
Может вы подскажете, что можно еще попробовать в данном случае?

2022-12-02 07:47 UTC, InnaRomankova commented
> уберите Thread Sleep. Change required


Я пробовала 2 варианта Wait, наиболее подходящие по смыслу, они не срабатывают:
getWait(10).until(ExpectedConditions
                .elementToBeClickable(By.xpath("//label[text()='Build periodically']")));
getWait(10).until(ExpectedConditions
                .presenceOfElementLocated(By.xpath("//label[text()='Build periodically']")));
...

Implicit Wait тоже не срабатывает в этом случае в CI. Локально у меня все проходит без Waits.
Может вы подскажете, что можно еще попробовать в данном случае?

2022-12-02 08:05 UTC, Stanislaw1349 commented
Сейчас не имею возможности посмотреть, за ПК буду часов через 10

2022-12-02 16:01 UTC, olpolezhaeva commented on src/test/java/FreestyleProjectSecondTest.java
> +        Thread.sleep(1000);
Мы уже не используем слип. Есть метод getWait()

2022-12-02 16:11 UTC, InnaRomankova commented on src/test/java/FreestyleProjectSecondTest.java
> +        Thread.sleep(1000);
Спасибо, что посмотрели мой код и сделали ревью. Вся проблема в том, что getWait() не работает для этого элемента. Поэтому я использовала Sleep.

2022-12-04 22:00 UTC, kirin608 approved these changes

2022-12-04 22:01 UTC, kirin608 reviewed
Failed tests:   testSelectBuildPeriodicallyCheckbox(FreestyleProjectSecondTest): element click intercepted: Element is not clickable at point (446, 1419)(..)

2022-12-07 19:57 UTC, Stanislaw1349 approved these changes
LGTM

2022-12-08 13:10 UTC, merged