RF | FreestyleProjectTest> testDisableProject
RedRoverSchool/JenkinsQA_05 pull request #995
Opened 2022-12-10 04:16 UTC by janarkqa

https://trello.com/c/nI5iUlJn/899-rf-freestyleprojecttest-testdisableproject

2022-12-11 03:15 UTC, SergeiKuznetsov commented
@janarkqa Приведите в порядок свою подпись
janarkqa <114713903+janarkqa@users.noreply.github.com>
это не очень понятная шифровка. Попробуйте подписыватся именем и фамилией, с реальным email.

2022-12-12 15:42 UTC, olpolezhaeva reviewed
Мне кажется, что создавая абстрактную базовую страницу, вы должны сразу отнаследовать от нее все такие уже существующие в проекте страницы конфигурации, а не только страницу, с которой работаете вы, и отметить Сергея для ревью.

2022-12-12 16:00 UTC, olpolezhaeva requested changes
Создавая абстрактную базовую страницу, вы должны сразу отнаследовать от нее все такие уже существующие в проекте, а не только страницу, с которой работаете вы.

2022-12-12 22:39 UTC, janarkqa commented
> Создавая абстрактную базовую страницу, вы должны сразу отнаследовать от нее все такие уже существующие в проекте, а не только страницу, с которой работаете вы.

Я собиралась это делать в другом таске, а не в этом.

2022-12-12 22:40 UTC, janarkqa commented
> Создавая абстрактную базовую страницу, вы должны сразу отнаследовать от нее все такие уже существующие в проекте, а не только страницу, с которой работаете вы.

Я собиралась это сделать отдельным RF таском

2022-12-13 13:34 UTC, olpolezhaeva commented
Создание абстрактных классов и рефакторинг всех страниц лучше проводить отдельным пиаром. Здесь оставить взаимодействие с обычными страницами.

2022-12-13 14:10 UTC, olpolezhaeva approved these changes
Создание абстрактных классов и рефакторинг всех страниц лучше проводить отдельным пиаром. Здесь оставить взаимодействие с обычными страницами.

2022-12-15 17:02 UTC, merged